# Generated by Django 5.2.8 on 2026-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biliapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='est_en_ligne',
            new_name='disponible_en_ligne',
        ),
        migrations.AddField(
            model_name='formation',
            name='disponible_presentiel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscriptionformation',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscriptionformation',
            name='modalite',
            field=models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel')], default='en_ligne', max_length=20),
        ),
    ]
