# Generated by Django 5.2.8 on 2026-05-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biliapp', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
