# Generated by Django 5.2.8 on 2026-05-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biliapp', '0008_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_messages/files/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
