# Generated by Django 5.2.8 on 2026-05-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biliapp', '0009_groupmessage_file_groupmessage_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(),
        ),
    ]
