# Generated by Django 5.2.8 on 2026-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biliapp', '0010_remove_groupmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='group_attachments/'),
        ),
        migrations.AlterField(
            model_name='galerie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galerie/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
